resources:
  repositories:
  - repository: puma_configs
    type: github
    endpoint: puma_gh_deployment
    name: OllyButters/puma_configs

  - repository: puma_web
    type: github
    endpoint: puma_gh_deployment
    name: OllyButters/puma_web

schedules:
  - cron: "32 1 * * *"
    displayName: Nightly build
    branches:
     include:
      - master
    always: true

jobs:
- job: RUN_PUMA
  timeoutInMinutes: 120
  pool:
    vmImage: 'Ubuntu 20.04'


  steps:
  - checkout: self
    path: 'puma'

  - checkout: puma_configs
    path: 'configs'

  - checkout: puma_web
    path: 'web'


  - bash: |

      cd source
      sudo -H pip3 install -r requirements.txt
  
    workingDirectory: $(Pipeline.Workspace)/puma
    displayName: 'Install Python deps'
    condition: succeeded()


  - bash: |

      cd config
      ln -s $(Pipeline.Workspace)/configs/config_ALSPAC.ini_master ALSPAC.ini

      cd ../source
      ./papers.py --config ALSPAC.ini

    workingDirectory: $(Pipeline.Workspace)/puma
    displayName: 'Run the pipeline'
    condition: succeeded()



  - bash: |

      sudo apt install tree -y
      pwd
      echo -e "\n#############################"
      echo -e "File tree: ##################"
      tree $(Pipeline.Workspace)

    displayName: 'Diagnostics'
