resources:
  repositories:
  - repository: puma_configs
    type: github
    endpoint: puma_gh_deployment
    name: OllyButters/puma_configs
    ref: master

  - repository: puma_web
    type: github
    endpoint: puma_gh_deployment
    name: OllyButters/puma_web
    ref: master

schedules:
  - cron: "32 1 * * *"
    displayName: Nightly build
    branches:
     include:
      - master
    always: true

jobs:
- job: RUN_PUMA
  timeoutInMinutes: 120
  pool:
    vmImage: 'Ubuntu 20.04'


  steps:
  - checkout: self
    path: 'puma'

  - checkout: puma_configs
    path: 'configs'

  - checkout: puma_web
    path: 'web'
    persistCredentials: true

  - bash: |

      cd source
      sudo -H pip3 install -r requirements.txt
  
    workingDirectory: $(Pipeline.Workspace)/puma
    displayName: 'Install Python deps'
    condition: succeeded()


  - bash: |

      cd config
      ln -s $(Pipeline.Workspace)/configs/config_ALSPAC.ini_master ALSPAC.ini

      cd ../source
      ./papers.py --config ALSPAC.ini

    workingDirectory: $(Pipeline.Workspace)/puma
    displayName: 'Run the pipeline'
    condition: succeeded()


  - bash: |
      
      # Git needs some config set to be able to push to a repo. 
      git config --global user.email "you@example.com"
      git config --global user.name "Azure pipeline"
      
      # This repo is checked out in detatched head state, so reconnect it here.
      git checkout master
      
      # It is possible that other commits have been made to the testStatus repo since it 
      # was checked out. i.e. other pipeline runs might have finished.
      git pull

      cp -r $(Pipeline.Workspace)/puma/html/alspac .

      git add .
      git commit -m "Automatically updating web files"
      git push

    workingDirectory: $(Pipeline.Workspace)/web
    displayName: 'Commit web files'
    condition: succeeded()





  - bash: |

      sudo apt install tree -y
      pwd
      echo -e "\n#############################"
      echo -e "File tree: ##################"
      tree $(Pipeline.Workspace)

    displayName: 'Diagnostics'
